## World Happiness Report

### Merging the tables from the years 2005 - 2009

In [25]:
import pandas as pd
import numpy as np

table2015 = pd.read_csv('WorldHappinessScore_2015.csv', delimiter = ';')
table2015["year"] = 2015
#table2015.head(30)

table2016 = pd.read_csv('WorldHappinessScore_2016.csv', delimiter = ';')
table2016["year"] = 2016
#table2016.head(30)

table2017 = pd.read_csv('WorldHappinessScore_2017.csv', delimiter = ';')
table2017["year"] = 2017
#table2017.head(30)

table2018 = pd.read_csv('WorldHappinessScore_2018.csv', delimiter = ';')
table2018["year"] = 2018
#table2018.head(30)

table2019 = pd.read_csv('WorldHappinessScore_2019.csv', delimiter = ';')
table2019["year"] = 2019
#table2019.head(30)

tables = [table2015, table2016, table2017, table2018, table2019]

#mergedTables = pd.concat(tables, axis=0, join='outer', ignore_index=False, keys=None,
          #levels=None, names=None, verify_integrity=False, copy=True)
mergedTables = pd.concat(tables)

In [23]:
mergedTables.head(300)

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption)
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357
3,Norway,4,7.522,1.45239,1.33095,0.88521,0.66973,0.36503
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957
...,...,...,...,...,...,...,...,...
137,Comoros,138,3.956,0.27509,0.60323,0.29981,0.15412,0.18437
138,Ivory Coast,139,3.916,0.55507,0.57576,0.04476,0.40663,0.15530
139,Cambodia,140,3.907,0.55604,0.53750,0.42494,0.58852,0.08092
140,Angola,141,3.866,0.84731,0.66366,0.04991,0.00589,0.08434
141,Niger,142,3.856,0.13270,0.60530,0.26162,0.38041,0.17176

In [35]:
mergedTables.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 782 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        782 non-null    object
 1   Happiness Rank                 782 non-null    int64
 2   Happiness Score                782 non-null    float64
 3   Economy (GDP per Capita)       782 non-null    float64
 4   Family                         782 non-null    float64
 5   Health (Life Expectancy)       782 non-null    float64
 6   Freedom                        782 non-null    float64
 7   Trust (Government Corruption)  781 non-null    float64
 8   year                           782 non-null    int64
dtypes: float64(6), int64(2), object(1)
memory usage: 61.1+ KB

In [36]:
mergedTables.to_csv(r'/Users/sabrinarubert/Git/worldHappinessReport/mergedTable.csv', index=False)